apiVersion: v1
kind: Service
metadata:
  name: ywti-service
spec:
  selector:
    app: ywti-app
  ports:
    - protocol: TCP
      port: 80         # We expose port 80 internally
      targetPort: 8080 # We forward to Tomcat's port 8080
  type: ClusterIP